language: python
python:
  - "2.7"
  - "3.5"
#clone demolog for example DB generation code
before_install:
  - cd ..
  - git clone https://bitbucket.org/TheChymera/demolog
  - cd LabbookDB
install:
  - travis_wait 20 pip install -r requirements.txt
  - pip install .
script: 
  - py.test
  - ./test_scripts.sh
