language: python
python:
  - "2.7"
  - "3.5"
#clone demolog for example DB generation code
before_install:
  - cd ..
  - git clone https://bitbucket.org/TheChymera/demolog
  - git clone https://github.com/TheChymera/behaviopy.git
  - (cd behaviopy && python setup.py install)
  - cd LabbookDB
install:
  - travis_wait 20 pip install -r requirements.txt
  - pip install .
script: 
  - ./test_scripts.sh
  - py.test
  - (cd labbookdb/examples && for f in *.py ; do python "$f" ; done)
